from recommender_app.utils.parsing_utils import extract_float, extract_int


KEY_MAPPING = {
    "Model": "name",
    "Year of manufacture": ("year_of_manufacture", extract_int),
    "Year": ("year_of_manufacture", extract_int),
    "Model year": ("year_of_manufacture", extract_int),
    "Type": "usage_style",
    "Engine size": ("displacement", extract_float),
    "Type of engine": "type_of_engine",
    "Engine details": "engine_details",
    "Power": ("power", extract_float),
    "Engine type": "type_of_engine",
    "Output": ("power", extract_float),
    "Power output": ("power", extract_float),
    "Top speed": ("top_speed", extract_float),
    "Torque": ("torque", extract_float),
    "Compression": ("compression_ratio", extract_float),
    "Bore x stroke": "bore_x_stroke",
    "Valves per cylinder": ("valves_per_cylinder", extract_int),
    "Fuel system": "fuel_system",
    "Fuel control": "fuel_control",
    "Lubrication system": "lubrification_system",
    "Cooling system": "cooling_system",
    "Gearbox": "transmission",
    "Transmission type": "transmission_type",
    "Clutch": "clutch",
    "Driveline": "drive_line",
    "Fuel consumption": ("fuel_consumption", extract_float),
    "Greenhouse gases": ("greenhouse_gas_emissions", extract_float),
    "Emission details": "emission_class",
    "Frame type": "frame_type",
    "Trail": ("trail", extract_float),
    "Front suspension": "front_suspension",
    "Front wheel travel": ("front_wheel_travel", extract_float),
    "Rear suspension": "rear_suspension",
    "Rear wheel travel": ("rear_wheel_travel", extract_float),
    "Front tire": "front_tire",
    "Rear tire": "rear_tire",
    "Front brakes": "front_brake",
    "Diameter1": ("front_brake_diameter", extract_float),
    "Diameter2": ("rear_brake_diameter", extract_float),
    "Rear brakes": "rear_brake",
    "Wheels": "wheels",
    "Dry weight": ("dry_weight", extract_float),
    "Seat height": ("seat_height", extract_float),
    "Overall length": ("overall_length", extract_float),
    "Overall width": ("overall_width", extract_float),
    "Ground clearance": ("ground_clearance", extract_float),
    "Wheelbase": ("wheelbase", extract_float),
    "Fuel capacity": ("fuel_capacity", extract_float),
    "Reserve capacity": ("reserve_capacity", extract_float),
    "Reserve fuel capacity": ("reserve_capacity", extract_float),
    "Color options": "color_options",
    "Starter": "starter_type",
    "Light": "light",
    "Comments": "bike_peculiarities",
    "Price as new": ("price", extract_float),
    "Power to weight ratio": ("power_to_weight_ratio", extract_float),
    "Power/weight ratio": ("power_to_weight_ratio", extract_float),
    "Effect": ("power", extract_float),
    "Model name": "name",
    "Year model": ("year_of_manufacture", extract_int),
    "Seat" : ("seat_number", extract_int),
    "Overall height": ("overall_height", extract_float),
    "Carrying capacity": ("carrying_capacity"),
    "Max RPM": ("max_rpm", extract_int),
    "Maximum RPM": ("max_rpm", extract_int),
    "Ignition": "ignition",
    "Factory warranty": "factory_warranty",
    "Category": "usage_style",
    "Exhaust system": "exhaust_system",
    "Displacement (cc)": ("displacement", extract_float),
    "Displacement": ("displacement", extract_float),
    "Motorcycle name": "name",
    "Oil capacity": ("oil_capacity", extract_float),
    "Weight incl. oil, gas, etc.": ("wet_weight", extract_float),
    "Weight incl. oil, gas, etc": ("wet_weight", extract_float),
    "Alternate seat height": ("alternative_seat_height", extract_float),
    "Rake (fork angle)": ("fork_angle", extract_float),
    "Electrical" : "battery",
    "Starter" : "starter",
    "Instruments": "strumentation",
}
