"""add tables version model brand for better data structure

Revision ID: 6b680e0d65b3
Revises: f1e9ee735997
Create Date: 2025-07-23 14:29:47.196014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b680e0d65b3'
down_revision = 'f1e9ee735997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('warranty', sa.String(length=100), nullable=True),
    sa.Column('optional', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('seat_height_min', sa.Float(), nullable=True),
    sa.Column('seat_height_max', sa.Float(), nullable=True),
    sa.Column('dry_weight', sa.Float(), nullable=True),
    sa.Column('wet_weight', sa.Float(), nullable=True),
    sa.Column('displacement', sa.Float(), nullable=True),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('stroke', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('cylinder_config', sa.String(length=100), nullable=True),
    sa.Column('cooling', sa.String(length=100), nullable=True),
    sa.Column('starter', sa.String(length=100), nullable=True),
    sa.Column('fuel_system', sa.String(length=100), nullable=True),
    sa.Column('bore', sa.Float(), nullable=True),
    sa.Column('stroke_length', sa.Float(), nullable=True),
    sa.Column('clutch', sa.String(length=100), nullable=True),
    sa.Column('valves', sa.Integer(), nullable=True),
    sa.Column('distribution', sa.String(length=100), nullable=True),
    sa.Column('ride_by_wire', sa.Boolean(), nullable=True),
    sa.Column('traction_control', sa.Boolean(), nullable=True),
    sa.Column('engine_maps', sa.String(length=100), nullable=True),
    sa.Column('power_hp', sa.Float(), nullable=True),
    sa.Column('power_rpm', sa.Integer(), nullable=True),
    sa.Column('torque_nm', sa.Float(), nullable=True),
    sa.Column('torque_rpm', sa.Integer(), nullable=True),
    sa.Column('emissions', sa.String(length=100), nullable=True),
    sa.Column('gearbox_type', sa.String(length=100), nullable=True),
    sa.Column('gears', sa.Integer(), nullable=True),
    sa.Column('fuel_capacity', sa.Float(), nullable=True),
    sa.Column('final_drive', sa.String(length=100), nullable=True),
    sa.Column('frame_type', sa.String(length=200), nullable=True),
    sa.Column('front_suspension', sa.String(length=300), nullable=True),
    sa.Column('front_travel', sa.Float(), nullable=True),
    sa.Column('rear_suspension', sa.String(length=300), nullable=True),
    sa.Column('rear_travel', sa.Float(), nullable=True),
    sa.Column('front_brake_type', sa.String(length=100), nullable=True),
    sa.Column('front_brake_size', sa.Float(), nullable=True),
    sa.Column('rear_brake_type', sa.String(length=100), nullable=True),
    sa.Column('rear_brake_size', sa.Float(), nullable=True),
    sa.Column('abs', sa.Boolean(), nullable=True),
    sa.Column('wheel_type', sa.String(length=100), nullable=True),
    sa.Column('front_wheel_size', sa.String(length=100), nullable=True),
    sa.Column('front_tire', sa.String(length=200), nullable=True),
    sa.Column('rear_wheel_size', sa.String(length=100), nullable=True),
    sa.Column('rear_tire', sa.String(length=200), nullable=True),
    sa.Column('battery', sa.String(length=200), nullable=True),
    sa.Column('battery_capacity', sa.String(length=100), nullable=True),
    sa.Column('battery_life', sa.String(length=100), nullable=True),
    sa.Column('secondary_battery', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions')
    op.drop_table('models')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
