"""enhancing version table

Revision ID: 717ee7a6c4c2
Revises: 1fe5598138a4
Create Date: 2025-07-24 13:24:48.649649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717ee7a6c4c2'
down_revision = '1fe5598138a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_height_from_ground', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wheelbase', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cylinder_disposition', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cylinder_inclination', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cylinder_inclination_v', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('depowered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reverse_gear', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('average_consumption', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_column('average_consumption')
        batch_op.drop_column('reverse_gear')
        batch_op.drop_column('depowered')
        batch_op.drop_column('cylinder_inclination_v')
        batch_op.drop_column('cylinder_inclination')
        batch_op.drop_column('cylinder_disposition')
        batch_op.drop_column('wheelbase')
        batch_op.drop_column('min_height_from_ground')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')

    # ### end Alembic commands ###
