"""add seat_number field to motorcycle table

Revision ID: 8cbdf1eb20b9
Revises: d013f94a8976
Create Date: 2025-07-16 08:50:12.678128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbdf1eb20b9'
down_revision = 'd013f94a8976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('seat_number')

    # ### end Alembic commands ###
