"""adding motorcycles table

Revision ID: d013f94a8976
Revises: 9c7d195d63c5
Create Date: 2025-07-16 08:33:35.669121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd013f94a8976'
down_revision = '9c7d195d63c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('usage_style', sa.String(length=100), nullable=True),
    sa.Column('displacement', sa.Float(), nullable=True),
    sa.Column('type_of_engine', sa.String(length=100), nullable=True),
    sa.Column('engine_details', sa.String(length=500), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('max_rpm', sa.Integer(), nullable=True),
    sa.Column('torque', sa.Float(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('bore_x_stroke', sa.String(length=100), nullable=True),
    sa.Column('valves_per_cylinder', sa.Integer(), nullable=True),
    sa.Column('fuel_system', sa.String(length=100), nullable=True),
    sa.Column('fuel_control', sa.String(length=100), nullable=True),
    sa.Column('ignition', sa.String(length=100), nullable=True),
    sa.Column('lubrification_system', sa.String(length=100), nullable=True),
    sa.Column('cooling_system', sa.String(length=100), nullable=True),
    sa.Column('transmission', sa.String(length=100), nullable=True),
    sa.Column('transmission_type', sa.String(length=100), nullable=True),
    sa.Column('clutch', sa.String(length=100), nullable=True),
    sa.Column('drive_line', sa.String(length=100), nullable=True),
    sa.Column('fuel_consumption', sa.Float(), nullable=True),
    sa.Column('fuel_tank_capacity', sa.Float(), nullable=True),
    sa.Column('greenhouse_gas_emissions', sa.Float(), nullable=True),
    sa.Column('emission_class', sa.String(length=100), nullable=True),
    sa.Column('power_to_weight_ratio', sa.Float(), nullable=True),
    sa.Column('exhaust_system', sa.String(length=200), nullable=True),
    sa.Column('frame_type', sa.String(length=100), nullable=True),
    sa.Column('fork_angle', sa.Float(), nullable=True),
    sa.Column('trail', sa.Float(), nullable=True),
    sa.Column('front_suspension', sa.String(length=100), nullable=True),
    sa.Column('front_wheel_travel', sa.Float(), nullable=True),
    sa.Column('rear_suspension', sa.String(length=100), nullable=True),
    sa.Column('rear_wheel_travel', sa.Float(), nullable=True),
    sa.Column('front_tire', sa.String(length=100), nullable=True),
    sa.Column('rear_tire', sa.String(length=100), nullable=True),
    sa.Column('front_brake', sa.String(length=100), nullable=True),
    sa.Column('front_brake_diameter', sa.Float(), nullable=True),
    sa.Column('rear_brake', sa.String(length=100), nullable=True),
    sa.Column('rear_brake_diameter', sa.Float(), nullable=True),
    sa.Column('wheels', sa.String(length=100), nullable=True),
    sa.Column('dry_weight', sa.Float(), nullable=True),
    sa.Column('wet_weight', sa.Float(), nullable=True),
    sa.Column('seat_height', sa.Float(), nullable=True),
    sa.Column('alternative_seat_height', sa.Float(), nullable=True),
    sa.Column('overall_length', sa.Float(), nullable=True),
    sa.Column('overall_width', sa.Float(), nullable=True),
    sa.Column('overall_height', sa.Float(), nullable=True),
    sa.Column('ground_clearance', sa.Float(), nullable=True),
    sa.Column('wheelbase', sa.Float(), nullable=True),
    sa.Column('fuel_capacity', sa.Float(), nullable=True),
    sa.Column('reserve_capacity', sa.Float(), nullable=True),
    sa.Column('carrying_capacity', sa.String(length=100), nullable=True),
    sa.Column('oil_capacity', sa.Float(), nullable=True),
    sa.Column('color_options', sa.String(length=200), nullable=True),
    sa.Column('starter_type', sa.String(length=100), nullable=True),
    sa.Column('light', sa.String(length=100), nullable=True),
    sa.Column('bike_peculiarities', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=200), nullable=True),
    sa.Column('top_speed', sa.Float(), nullable=True),
    sa.Column('factory_warranty', sa.String(length=200), nullable=True),
    sa.Column('battery', sa.String(length=100), nullable=True),
    sa.Column('starter', sa.String(length=100), nullable=True),
    sa.Column('strumentation', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motorcycles')
    # ### end Alembic commands ###
