from recommender_app.extensions import db

class Motorcycle(db.Model):
    __tablename__ = 'motorcycles'

    id = db.Column(db.Integer, primary_key=True)

    full_name = db.Column(db.String(200), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    brand = db.Column(db.String(100), nullable=False)
    year_of_manufacture = db.Column(db.Integer, nullable=True)
    usage_style = db.Column(db.String(100), nullable=True)
    ## Engine specifications
    displacement = db.Column(db.Float, nullable=True)
    type_of_engine = db.Column(db.String(100), nullable=True)
    engine_details = db.Column(db.String(500), nullable=True)
    power = db.Column(db.Float, nullable=True)
    max_rpm = db.Column(db.Integer, nullable=True)
    torque = db.Column(db.Float, nullable=True)
    compression_ratio = db.Column(db.Float, nullable=True)
    bore_x_stroke = db.Column(db.String(100), nullable=True)
    valves_per_cylinder = db.Column(db.Integer, nullable=True)
    fuel_system = db.Column(db.String(100), nullable=True)
    fuel_control = db.Column(db.String(100), nullable=True)
    ignition = db.Column(db.String(100), nullable=True)
    lubrification_system = db.Column(db.String(100), nullable=True)
    cooling_system = db.Column(db.String(100), nullable=True)
    transmission = db.Column(db.String(100), nullable=True)
    transmission_type = db.Column(db.String(100), nullable=True)
    clutch = db.Column(db.String(100), nullable=True)
    drive_line = db.Column(db.String(100), nullable=True)
    fuel_consumption = db.Column(db.Float, nullable=True)
    fuel_tank_capacity = db.Column(db.Float, nullable=True)
    greenhouse_gas_emissions = db.Column(db.Float, nullable=True)
    emission_class = db.Column(db.String(100), nullable=True)
    power_to_weight_ratio = db.Column(db.Float, nullable=True)
    exhaust_system = db.Column(db.String(200), nullable=True)
    ## Chassis specifications
    frame_type = db.Column(db.String(100), nullable=True)
    fork_angle = db.Column(db.Float, nullable=True)
    trail = db.Column(db.Float, nullable=True)
    front_suspension = db.Column(db.String(100), nullable=True)
    front_wheel_travel = db.Column(db.Float, nullable=True)
    rear_suspension = db.Column(db.String(100), nullable=True)
    rear_wheel_travel = db.Column(db.Float, nullable=True)
    front_tire = db.Column(db.String(100), nullable=True)
    rear_tire = db.Column(db.String(100), nullable=True)
    front_brake = db.Column(db.String(100), nullable=True)
    front_brake_diameter = db.Column(db.Float, nullable=True)
    rear_brake = db.Column(db.String(100), nullable=True)
    rear_brake_diameter = db.Column(db.Float, nullable=True)
    wheels = db.Column(db.String(100), nullable=True)
    ## Dimensions and weight
    dry_weight = db.Column(db.Float, nullable=True)
    wet_weight = db.Column(db.Float, nullable=True)
    seat_height = db.Column(db.Float, nullable=True)
    alternative_seat_height = db.Column(db.Float, nullable=True)
    overall_length = db.Column(db.Float, nullable=True)
    overall_width = db.Column(db.Float, nullable=True)
    overall_height = db.Column(db.Float, nullable=True)
    ground_clearance = db.Column(db.Float, nullable=True)
    wheelbase = db.Column(db.Float, nullable=True)
    fuel_capacity = db.Column(db.Float, nullable=True)
    reserve_capacity = db.Column(db.Float, nullable=True)
    carrying_capacity = db.Column(db.String(100), nullable=True)
    oil_capacity = db.Column(db.Float, nullable=True)
    ## Additional specifications
    color_options = db.Column(db.String(200), nullable=True)
    starter_type = db.Column(db.String(100), nullable=True)
    light = db.Column(db.String(100), nullable=True)
    bike_peculiarities = db.Column(db.Text, nullable=True)
    price = db.Column(db.Float, nullable=True)
    source_url = db.Column(db.String(200), nullable=True)
    top_speed = db.Column(db.Float, nullable=True)
    factory_warranty = db.Column(db.String(200), nullable=True)
